server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - json:
      expressions:
        timestamp: timestamp
        message: message
        thread_name: thread_name
        level: level
        trace_id: traceId
        span_id: spanId
  - labels:
      level:
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /tmp/test.log
